// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/pages/about.vue')['default']
    App: typeof import('./src/App.vue')['default']
    AppMain: typeof import('./src/layout/components/AppMain.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/pages/home.vue')['default']
    Item: typeof import('./src/layout/components/Sidebar/Item.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    Sidebar: typeof import('./src/layout/components/Sidebar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}

export { }
