// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/pages/about.vue')['default']
    App: typeof import('./src/App.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/pages/home.vue')['default']
  }
}

export { }
